// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adohmwksanyivucvnmbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkb2htd2tzYW55aXZ1Y3ZubWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTAxMzgsImV4cCI6MjA3NDQyNjEzOH0.4D35CXtadjmsmryULY8AzTv9LBf3magkyNE-vw7Im4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});